import {lazy,Suspense} from 'react';
import {useTranslation} from 'react-i18next';
import {ArrowUpRight,LockKeyhole} from 'lucide-react';
import {CallToAction,href,PageHero,SectionHeader,TopCard} from '../components/Shell';
export {Home} from './Home';
import {ClosedLoop} from '../components/ClosedLoop';
import {Settlement} from '../components/Settlement';
import {ContactForm} from '../components/ContactForm';
const ForecastDemo=lazy(()=>import('../components/ForecastDemo').then(m=>({default:m.ForecastDemo})));
const Waterfall=lazy(()=>import('../components/Waterfall').then(m=>({default:m.Waterfall})));
const colors=['var(--blue)','var(--gold)','var(--teal)','var(--violet)','var(--green)','var(--red)'];
type Card={title:string,body:string};
function Cards({items,offset=0}:{items:Card[],offset?:number}){return <div className="cards-grid">{items.map((v,i)=><TopCard key={i} index={`0${i+1}`} color={colors[(i+offset)%colors.length]} {...v}/>)}</div>}
function LinkedBanner({keyName,route}:{keyName:string,route:'contact'|'solution'|'investors'}){const {t,i18n}=useTranslation();return <a className="linked-banner" href={href(i18n.language,route)}><span>{t(keyName)}</span><ArrowUpRight/></a>}
export function Problem(){const {t}=useTranslation();const cards=t('problem.cards',{returnObjects:true}) as Card[];return <><PageHero eyebrow={t('problem.eyebrow')} title={t('problem.title')} lead={t('problem.lead')}/><section className="section"><div className="wrap"><Cards items={cards} offset={5}/><div className="problem-chain mono">{t('problem.chain')}</div><p className="section-outro">{t('problem.outro')}</p><LinkedBanner keyName="common.learn" route="solution"/></div></section></>}
export function Solution(){const {t}=useTranslation();return <><PageHero eyebrow={t('solution.eyebrow')} title={t('solution.title')} lead={t('solution.lead')}/><section className="section"><div className="wrap"><ClosedLoop/></div></section></>}
export function CTGOT(){const {t}=useTranslation();const cards=t('ctgot.gates',{returnObjects:true}) as Card[];return <><PageHero eyebrow={t('ctgot.eyebrow')} title={t('ctgot.title')} lead={t('ctgot.lead')}/><section className="section"><div className="wrap"><SectionHeader index="01" heading={t('ctgot.gatesTitle')}/><Cards items={cards}/></div></section><section className="section alt-section"><div className="wrap"><SectionHeader index="02" heading={t('ctgot.demoTitle')}/><Suspense fallback={<div className="loading-panel" aria-busy="true"/>}><ForecastDemo/></Suspense></div></section></>}
export function Investors(){const {t}=useTranslation();return <><PageHero eyebrow={t('investors.eyebrow')} title={t('investors.title')} lead={t('investors.lead')}><p className="qualified"><LockKeyhole size={18}/>{t('common.qualified')}</p></PageHero><section className="section"><div className="wrap"><div className="metric-row investor-metrics">{([1,2,3] as const).map(n=><div key={n}><strong>{t(`investors.target${n}`)}</strong><span>{t(`investors.target${n}Label`)}</span></div>)}</div><p className="small source-note">{t('investors.targetNote')}</p><div className="cards-grid two"><TopCard color={colors[1]} index="01" title={t('investors.structure')} body={t('investors.structureBody')}/><TopCard color={colors[5]} index="02" title={t('investors.collateral')} body={t('investors.collateralBody')}/></div><p className="todo-line">{t('investors.custodyTodo')}</p></div></section><section className="section alt-section"><div className="wrap"><SectionHeader index="02" heading={t('investors.waterfall')}/><ol className="tier-list">{(t('investors.tiers',{returnObjects:true}) as string[]).map(v=><li key={v}>{v}</li>)}</ol><Suspense fallback={<div className="loading-panel" aria-busy="true"/>}><Waterfall/></Suspense></div></section><section className="section"><div className="wrap"><SectionHeader index="03" heading={t('investors.pathsTitle')}/><Settlement/></div></section><section className="section alt-section"><div className="wrap access-banner"><div><h2>{t('investors.cta')}</h2><p>{t('investors.gateNotice')}</p></div><CallToAction>{t('common.request')}</CallToAction></div></section></>}
export function Promoters(){const {t}=useTranslation();const cards=t('promoters.cards',{returnObjects:true}) as Card[];return <><PageHero eyebrow={t('promoters.eyebrow')} title={t('promoters.title')} lead={t('promoters.lead')}><CallToAction query="?type=promoter">{t('promoters.cta')}</CallToAction></PageHero><section className="section"><div className="wrap"><Cards items={cards}/></div></section></>}
export function Technology(){const {t}=useTranslation();const layers=t('technology.layers',{returnObjects:true}) as Card[];return <><PageHero eyebrow={t('technology.eyebrow')} title={t('technology.title')} lead={t('technology.lead')}/><section className="section"><div className="wrap"><Cards items={layers}/><details className="technical"><summary>{t('technology.techTitle')}</summary><p>{t('technology.techBody')}</p></details><p className="small source-note">{t('technology.note')}</p></div></section></>}
export function Market(){const {t}=useTranslation();const fees=t('market.feeItems',{returnObjects:true}) as Array<{value:string,label:string}>;return <><PageHero eyebrow={t('market.eyebrow')} title={t('market.title')} lead={t('market.lead')}/><section className="section"><div className="wrap"><div className="market-stats"><div><strong>{t('market.market1')}</strong><span>{t('market.market1Label')}</span></div><div><strong>{t('market.market2')}</strong><span>{t('market.market2Label')}</span></div></div><SectionHeader index="01" heading={t('market.fees')}/><div className="fee-grid">{fees.map((f,i)=><div key={i}><strong>{f.value}</strong><span>{f.label}</span></div>)}</div><p className="small source-note">{t('market.note')}</p></div></section></>}
export function Pilot(){const {t}=useTranslation();const phases=t('pilot.phases',{returnObjects:true}) as Array<{time:string,title:string,body:string}>;return <><PageHero eyebrow={t('pilot.eyebrow')} title={t('pilot.title')} lead={t('pilot.lead')}/><section className="section"><div className="wrap"><div className="pilot-timeline">{phases.map((p,i)=><article key={i}><span className="mono">{p.time}</span><h2>{p.title}</h2><p>{p.body}</p></article>)}</div><div className="access-banner"><div><h2>{t('pilot.ask')}</h2><p>{t('pilot.askBody')}</p></div><CallToAction>{t('common.request')}</CallToAction></div></div></section></>}
export function Team(){const {t}=useTranslation();const members=t('team.members',{returnObjects:true}) as Array<{name:string,role:string,bio:string}>;return <><PageHero eyebrow={t('team.eyebrow')} title={t('team.title')}/><section className="section"><div className="wrap"><div className="team-grid">{members.map((m,i)=><article key={m.name} className="team-card"><div className="monogram" aria-hidden="true">{m.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</div><p className="eyebrow">0{i+1} / {m.role}</p><h2>{m.name}</h2><p>{m.bio}</p></article>)}</div><p className="small source-note">{t('team.source')}</p></div></section></>}
export function Contact(){const {t}=useTranslation();return <><PageHero eyebrow={t('contact.eyebrow')} title={t('contact.title')} lead={t('contact.lead')}/><section className="section"><div className="wrap narrow"><ContactForm/></div></section></>}
export function Legal(){const {t}=useTranslation();const sections=t('legal.sections',{returnObjects:true}) as Array<{title:string,body:string}>;return <><PageHero eyebrow={t('legal.eyebrow')} title={t('legal.title')}/><section className="section"><div className="wrap narrow"><div className="legal-sections">{sections.map((v,i)=><article key={i}><span className="section-index">0{i+1}</span><h2>{v.title}</h2><p>{v.body}</p></article>)}</div><p className="todo-line">{t('legal.todo')}</p></div></section></>}
export function Design(){const {t}=useTranslation();const names=t('design.colorNames',{returnObjects:true}) as string[];const cards=t('design.cards',{returnObjects:true}) as string[];return <><PageHero eyebrow={t('design.eyebrow')} title={t('design.title')} lead={t('design.intro')}/><section className="section"><div className="wrap"><SectionHeader index="01" heading={t('design.colors')}/><div className="swatches">{names.map((v,i)=><div key={i}><span style={{background:colors[i]}}/><strong>{v}</strong><code>{['--blue','--gold','--teal','--violet','--green','--red'][i]}</code></div>)}</div><SectionHeader index="02" heading={t('design.type')}/><p>{t('design.typeText')}</p><div className="type-examples"><span className="brand">CORTEX</span><span>{t('design.typeExample')}</span><span className="mono">01 / 02 / 03</span></div><SectionHeader index="03" heading={t('design.components')}/><div className="cards-grid"><TopCard color={colors[0]} title={cards[0]} body={t('home.pillar1Body')} index="01"/><TopCard color={colors[5]} title={cards[1]} body={t('ctgot.demoIntro')} index="02"/><TopCard color={colors[1]} title={cards[2]} body={t('market.market1Label')} index="03"/></div><div className="design-button"><CallToAction>{cards[3]}</CallToAction></div></div></section></>}
