import {useState,type FormEvent} from 'react';
import {useTranslation} from 'react-i18next';
import {ContactSchema} from '../lib/contact';
import {href} from './Shell';
const endpoint=(import.meta.env.VITE_CONTACT_ENDPOINT||'').trim();
const empty={name:'',organization:'',country:'',role:'',size:'',message:'',consent:false,website:''};
type Field=keyof typeof empty;
export function ContactForm(){const {t,i18n}=useTranslation();const [type,setType]=useState<'investor'|'promoter'>(()=>new URLSearchParams(location.search).get('type')==='promoter'?'promoter':'investor');const [fields,setFields]=useState(empty);const [errors,setErrors]=useState<Record<string,string>>({});const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle');
 function update(key:Field,value:string|boolean){setFields(prev=>({...prev,[key]:value}));setErrors(prev=>({...prev,[key]:''}));setState('idle')}
 async function submit(e:FormEvent){e.preventDefault();if(fields.website)return;const parsed=ContactSchema.safeParse({...fields,type});if(!parsed.success){const problems:Record<string,string>={};for(const issue of parsed.error.issues)problems[String(issue.path[0])]=issue.code==='too_big'?t('contact.form.tooLong'):t('contact.form.invalid');setErrors(problems);setState('error');return}if(!endpoint){setState('error');return}setState('sending');try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});if(!response.ok)throw Error(String(response.status));setState('success');setFields(empty)}catch(err){if(import.meta.env.DEV)console.error('Contact request failed',err);setState('error')}}
 const input=(key:Field,label:string,props:{type?:string,maxLength?:number}={})=><label className="field" key={key}><span>{label}</span><input value={String(fields[key])} onChange={e=>update(key,e.target.value)} maxLength={props.maxLength||120} type={props.type||'text'} required aria-invalid={!!errors[key]} aria-describedby={errors[key]?`error-${key}`:undefined}/>{errors[key]&&<small id={`error-${key}`} className="error-text">{errors[key]}</small>}</label>;
 return <form className="contact-form" onSubmit={submit} noValidate><div className="contact-switch" role="group" aria-label={t('contact.title')}><button type="button" aria-pressed={type==='investor'} className={type==='investor'?'selected':''} onClick={()=>{setType('investor');setState('idle')}}>{t('contact.investor')}</button><button type="button" aria-pressed={type==='promoter'} className={type==='promoter'?'selected':''} onClick={()=>{setType('promoter');setState('idle')}}>{t('contact.promoter')}</button></div><div className="form-grid">{input('name',t('contact.form.name'),{maxLength:100})}{input('organization',t('contact.form.organization'))}{input('country',t('contact.form.country'),{maxLength:80})}{input('role',t('contact.form.role'),{maxLength:80})}{input('size',t(type==='investor'?'contact.form.sizeInvestor':'contact.form.sizePromoter'),{maxLength:80})}</div><label className="field message-field"><span>{t('contact.form.message')}</span><textarea value={fields.message} maxLength={2000} rows={5} required aria-invalid={!!errors.message} onChange={e=>update('message',e.target.value)}/>{errors.message&&<small className="error-text">{errors.message}</small>}</label><div className="honeypot" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={fields.website} onChange={e=>update('website',e.target.value)}/></label></div><label className="consent"><input type="checkbox" checked={fields.consent} onChange={e=>update('consent',e.target.checked)} required aria-invalid={!!errors.consent}/><span>{t('contact.form.consent')} <a href={href(i18n.language,'legal')}>{t('nav.legal')}</a></span></label>{errors.consent&&<small className="error-text">{errors.consent}</small>}
 {!endpoint&&<p className="form-notice" role="status">{t('contact.form.unconfigured')}</p>}{state==='error'&&endpoint&&<p role="alert" className="error-text">{Object.keys(errors).length?t('contact.form.validation'):t('contact.form.error')}</p>}{state==='success'&&<p role="status" className="success-text">{t('contact.form.success')}</p>}<button className="button primary" type="submit" disabled={!endpoint||state==='sending'}>{t(state==='sending'?'contact.form.sending':'contact.form.send')}</button></form>}
