import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {ResponsiveContainer,Area,ComposedChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ReferenceLine,Legend} from 'recharts';
import {sampleEvents,illustrativeGate} from '../data/schema';
export function ForecastDemo(){const {t,i18n}=useTranslation();const [id,setId]=useState(sampleEvents[0].func_id);const event=sampleEvents.find(e=>e.func_id===id)!;
 const chart=event.p50.map((p50,i)=>({period:Math.round(i*100/(event.p50.length-1)),p50,p90:event.p90[i],band:event.p90[i]-p50}));
 const fmt=(n:number)=>new Intl.NumberFormat(i18n.language).format(n);
 return <div className="demo-panel scanline"><div className="demo-top"><div><p className="eyebrow">{t('common.illustrative')}</p><h3>{t('ctgot.demoTitle')}</h3><p>{t('ctgot.demoIntro')}</p></div><label className="field select-field"><span>{t('ctgot.event')}</span><select value={id} onChange={e=>setId(e.target.value)}>{sampleEvents.map(e=><option key={e.func_id} value={e.func_id}>{e.func_id} · {t(`ctgot.sampleNames.${e.func_id}.show_name`)}</option>)}</select></label></div>
 <div className="sample-head"><div><span className="mono muted">{event.func_id} / {event.fecha}</span><h4>{t(`ctgot.sampleNames.${event.func_id}.show_name`)}</h4><span>{t(`ctgot.sampleNames.${event.func_id}.venue`)}</span></div><span className={`gate ${illustrativeGate(event)?'pass':'fail'}`}>{t('ctgot.gate')}: {t(illustrativeGate(event)?'ctgot.pass':'ctgot.fail')}</span></div>
 <div className="metric-row"><div><span>{t('ctgot.capacity')}</span><strong>{fmt(event.capacidad)}</strong></div><div><span>{t('ctgot.be')}</span><strong>{fmt(event.break_even)}</strong></div><div><span>{t('ctgot.pbe')}</span><strong>{Math.round(event.p_break_even*100)} %</strong></div></div>
 <div className="chart-wrap" role="img" aria-label={`${t('ctgot.curve')}: ${event.func_id}, ${t('ctgot.p50')} ${fmt(event.p50.at(-1)!)}, ${t('ctgot.p90')} ${fmt(event.p90.at(-1)!)}, ${t('ctgot.be')} ${fmt(event.break_even)}`}><ResponsiveContainer width="100%" height={320}><ComposedChart data={chart} margin={{top:12,right:20,bottom:8,left:0}}><CartesianGrid stroke="var(--grid)" vertical={false}/><XAxis dataKey="period" unit="%" stroke="var(--muted)" tickLine={false}/><YAxis domain={[0,event.capacidad]} stroke="var(--muted)" tickLine={false} width={48} tickFormatter={fmt}/><Tooltip contentStyle={{background:'var(--surface)',color:'var(--text)',border:'1px solid var(--border)',borderRadius:10}} formatter={(value,name)=>[fmt(Number(value)),name]} /><Legend/><Area type="monotone" dataKey="p50" stackId="band" stroke="#63a5ee" fill="#63a5ee" fillOpacity={.13} name={t('ctgot.p50')}/><Area type="monotone" dataKey="band" stackId="band" stroke="none" fill="#63a5ee" fillOpacity={.18} name={t('ctgot.p90')+' − '+t('ctgot.p50')}/><Line type="monotone" dataKey="p90" stroke="#8ec5fb" strokeWidth={2} dot={false} name={t('ctgot.p90')}/><ReferenceLine y={event.break_even} stroke="#e6b463" strokeDasharray="5 5" label={{value:t('ctgot.be'),position:'insideTopRight',fill:'#e6b463',fontSize:12}}/></ComposedChart></ResponsiveContainer></div>
 <div className="chart-footer mono"><span>{t('ctgot.horizon')} / 0–100 %</span><span>{t('ctgot.generated')}: {event.generated_at.slice(0,10)}</span></div><details className="data-detail"><summary>{t('ctgot.table')}</summary><div className="table-scroll"><table><thead><tr><th>{t('ctgot.horizon')}</th><th>{t('ctgot.p50')}</th><th>{t('ctgot.p90')}</th></tr></thead><tbody>{chart.map(row=><tr key={row.period}><td>{row.period} %</td><td>{fmt(row.p50)}</td><td>{fmt(row.p90)}</td></tr>)}</tbody></table></div></details>
 </div>}
