import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {calculateWaterfall,type WaterfallInputType} from '../lib/waterfall';
const defaults:WaterfallInputType={tickets:180000,sponsors:20000,merch:12000,food:8000,costs:85000,principal:90000,preferredPct:5,feePct:3,promoterPct:60};
const inputs:[keyof WaterfallInputType,string][]=[['tickets','tickets'],['sponsors','sponsors'],['merch','merch'],['food','food'],['costs','costs'],['principal','principal'],['preferredPct','return'],['feePct','fee'],['promoterPct','promoter']];
export function Waterfall(){const {t,i18n}=useTranslation();const [v,setV]=useState(defaults);const out=calculateWaterfall(v);const fmt=(n:number)=>new Intl.NumberFormat(i18n.language,{maximumFractionDigits:2,minimumFractionDigits:0}).format(n);const money=(n:number)=>`$${fmt(n)}`;
 const portions=[{k:'senior',n:out.senior,color:'var(--gold)'},{k:'platform',n:out.platform,color:'var(--blue)'},{k:'promoter',n:out.promoter,color:'var(--teal)'},{k:'artist',n:out.artist,color:'var(--violet)'}] as const;
 return <div className="calculator scanline"><p className="eyebrow">{t('common.illustrativeCalc')}</p><div className="calc-grid"><div><h3>{t('investors.calculator')}</h3><p>{t('investors.calculatorIntro')}</p><div className="input-grid">{inputs.map(([key,label])=><label className="field" key={key}><span>{t(`investors.fields.${label}`)} {['preferredPct','feePct','promoterPct'].includes(key)?'':'(USD)'}</span><input type="number" min="0" max={key.endsWith('Pct')?'100':undefined} step={key.endsWith('Pct')?'0.1':'100'} value={v[key]} onChange={e=>setV(prev=>({...prev,[key]:Math.max(0,Math.min(key.endsWith('Pct')?100:1000000000,Number(e.target.value)||0))}))}/></label>)}</div><p className="mono small">{t('investors.fields.artist')}: {100-v.promoterPct} %</p></div>
 <div className="calc-output" aria-live="polite"><div className="output-feature"><span>{t('investors.out.net')}</span><strong>{money(out.net)}</strong></div><div className="stacked" role="img" aria-label={portions.map(p=>`${t(`investors.out.${p.k}`)} ${money(p.n)}`).join(', ')}>{portions.map(p=><span key={p.k} style={{width:`${out.net>0?(p.n/out.net)*100:0}%`,background:p.color}} title={`${t(`investors.out.${p.k}`)}: ${money(p.n)}`}/>)}</div><div className="pay-list">{portions.map((p,i)=><div key={p.k}><span><i style={{background:p.color}}/> {i+1}. {t(`investors.out.${p.k}`)}</span><strong>{money(p.n)}</strong></div>)}</div><div className="calc-alert"><span>{t('investors.out.shortfall')}</span><strong>{money(out.unpaid)}</strong></div>{out.deficit>0&&<div className="calc-alert"><span>{t('investors.out.deficit')}</span><strong>{money(out.deficit)}</strong></div>}<p className="small formula">{t('investors.formula')}</p></div></div></div>}
